
[[constraint]]
  branch = "master"
  name = "github.com/function61/gokit"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/function61/eventhorizon"
